import { execFileSync } from 'node:child_process';
import {
  appendFileSync,
  mkdirSync,
  mkdtempSync,
  renameSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { findMigrationViolations } from './migration-policy';

// Real-git tripwire for the migration immutability gate. The unit tests in
// migration-policy.test.ts mock execGit, so they pin the parser and the
// base-resolution chain but not the agreement between the shelled-out command
// and git's actual `--name-status` output shape. These tests run the real
// command against throwaway repos (distinct from lockfile-policy.test.ts's
// real-file tripwire) so a change to the pathspec, rename detection, or the
// status prefix format goes red instead of silently passing.
//
// changes are committed so the diff compares two commits, as the CI gate does
// between the merge base and the PR head (a bare working-tree move would show
// as D with the new file untracked, which is not the CI shape). The push
// scenario runs against the real resolution chain instead of a baseRef, pinning
// the throw when a force-push leaves GITHUB_BEFORE unresolvable.
const TEMP_DIRS: string[] = [];

afterEach(() => {
  while (TEMP_DIRS.length > 0) {
    const dir = TEMP_DIRS.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

function git(cwd: string, args: string[]): void {
  execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

function commitAll(dir: string, message: string): void {
  git(dir, ['add', '-A']);
  git(dir, ['commit', '-q', '-m', message]);
}

interface Repo {
  dir: string;
  base: string;
}

function initMigrationRepo(): Repo {
  const dir = mkdtempSync(join(tmpdir(), 'migration-policy-real-git-'));
  TEMP_DIRS.push(dir);
  git(dir, ['init', '-q']);
  git(dir, ['config', 'user.email', 'test@example.com']);
  git(dir, ['config', 'user.name', 'Migration Policy Test']);
  mkdirSync(join(dir, 'prisma/migrations/20260403092044_init'), { recursive: true });
  writeFileSync(
    join(dir, 'prisma/migrations/20260403092044_init/migration.sql'),
    'CREATE TABLE "MigrationsTest" ("id" INTEGER);\n',
  );
  writeFileSync(
    join(dir, 'prisma/migrations/migration_lock.toml'),
    '# Please do not edit this file manually\nprovider = "postgresql"\n',
  );
  commitAll(dir, 'init applied migration');
  const base = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: dir, encoding: 'utf8' }).trim();
  return { dir, base };
}

function violationsFor(dir: string, base: string) {
  return findMigrationViolations({ cwd: dir, env: {}, baseRef: base });
}

describe('findMigrationViolations against real git', () => {
  it('flags an applied migration edited after being applied', () => {
    const { dir, base } = initMigrationRepo();
    appendFileSync(
      join(dir, 'prisma/migrations/20260403092044_init/migration.sql'),
      'ALTER TABLE "MigrationsTest" ADD COLUMN "x" INTEGER;\n',
    );

    expect(violationsFor(dir, base)).toEqual([
      {
        type: 'modified',
        status: 'M',
        path: 'prisma/migrations/20260403092044_init/migration.sql',
      },
    ]);
  });

  it('flags a deleted applied migration', () => {
    const { dir, base } = initMigrationRepo();
    rmSync(join(dir, 'prisma/migrations/20260403092044_init'), {
      recursive: true,
      force: true,
    });

    expect(violationsFor(dir, base)).toEqual([
      {
        type: 'deleted',
        status: 'D',
        path: 'prisma/migrations/20260403092044_init/migration.sql',
      },
    ]);
  });

  it('flags a renamed applied migration', () => {
    const { dir, base } = initMigrationRepo();
    renameSync(
      join(dir, 'prisma/migrations/20260403092044_init'),
      join(dir, 'prisma/migrations/20260403092044_init_renamed'),
    );
    commitAll(dir, 'rename applied migration');

    expect(violationsFor(dir, base)).toEqual([
      {
        type: 'renamed',
        status: 'R100',
        oldPath: 'prisma/migrations/20260403092044_init/migration.sql',
        path: 'prisma/migrations/20260403092044_init_renamed/migration.sql',
      },
    ]);
  });

  it('flags an applied migration.sql renamed to a non-.sql path', () => {
    const { dir, base } = initMigrationRepo();
    renameSync(
      join(dir, 'prisma/migrations/20260403092044_init/migration.sql'),
      join(dir, 'prisma/migrations/20260403092044_init/schema.txt'),
    );
    commitAll(dir, 'rename applied migration.sql to schema.txt');

    expect(violationsFor(dir, base)).toEqual([
      {
        type: 'renamed',
        status: 'R100',
        oldPath: 'prisma/migrations/20260403092044_init/migration.sql',
        path: 'prisma/migrations/20260403092044_init/schema.txt',
      },
    ]);
  });

  it('fails closed on a push whose GITHUB_BEFORE was rewritten out of history', () => {
    const { dir } = initMigrationRepo();
    const before = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: dir,
      encoding: 'utf8',
    }).trim();

    // Simulate a force-push: rewrite the branch so the original tip becomes an
    // orphan, point origin/main at the new tip, and prune the old objects so
    // GITHUB_BEFORE is genuinely unresolvable (a CI fetch never receives
    // objects that were pushed away).
    git(dir, ['checkout', '-q', '--orphan', 'rewritten']);
    git(dir, ['rm', '-rqf', '--ignore-unmatch', '.']);
    mkdirSync(join(dir, 'prisma/migrations/20260403092044_init'), { recursive: true });
    writeFileSync(
      join(dir, 'prisma/migrations/20260403092044_init/migration.sql'),
      'CREATE TABLE "MigrationsTest" ("id" INTEGER);\nALTER TABLE "MigrationsTest" ADD COLUMN "amended" INTEGER;\n',
    );
    commitAll(dir, 'rewritten tip contains an amended applied migration');
    git(dir, ['update-ref', 'refs/remotes/origin/main', 'HEAD']);
    git(dir, ['update-ref', 'refs/heads/main', 'HEAD']);
    git(dir, ['reflog', 'expire', '--expire=now', '--all']);
    git(dir, ['gc', '--prune=now', '-q']);

    expect(() =>
      findMigrationViolations({
        cwd: dir,
        env: { GITHUB_EVENT_NAME: 'push', GITHUB_BEFORE: before },
      }),
    ).toThrow(/refusing to pass/);
  });

  it('ignores a newly added migration', () => {
    const { dir, base } = initMigrationRepo();
    mkdirSync(join(dir, 'prisma/migrations/20260912120000_new_feature'), {
      recursive: true,
    });
    writeFileSync(
      join(dir, 'prisma/migrations/20260912120000_new_feature/migration.sql'),
      'CREATE TABLE "New" ("id" INTEGER);\n',
    );
    commitAll(dir, 'add new migration');

    expect(violationsFor(dir, base)).toEqual([]);
  });

  it('ignores edits to migration_lock.toml', () => {
    const { dir, base } = initMigrationRepo();
    appendFileSync(
      join(dir, 'prisma/migrations/migration_lock.toml'),
      '\nprovider = "postgresql"\n',
    );

    expect(violationsFor(dir, base)).toEqual([]);
  });

  it('reports no violations on a clean working tree', () => {
    const { dir, base } = initMigrationRepo();

    expect(violationsFor(dir, base)).toEqual([]);
  });
});
