/**
 * Records that a route's source changed without changing what it renders.
 *
 * `check-visual-baseline-freshness` flags a route whose source moved in this
 * diff while its baseline did not. Usually that means someone forgot to
 * regenerate. Sometimes the change genuinely does not render — a predicate
 * extracted into a shared module, an import reordered — and then the
 * regenerated screenshot is byte-identical, git has nothing to record, and
 * the route can never clear on its own.
 *
 * This writes the missing record. It does NOT take the operator's word for
 * it: it runs the regeneration itself and refuses if a single baseline byte
 * moved, because a change that moved a pixel needs its new baseline
 * committed, not an attestation.
 *
 * Baselines are macOS-only (`-darwin.png`), so this refuses to run anywhere
 * else — a Linux digest would attest to bytes CI will never see.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import {
  ROUTE_BASELINES,
  ATTESTATION_PATH,
  hashFiles,
  type AttestationMap,
  type BaselineAttestation,
} from '../src/lib/visual-baseline-freshness';

function fail(message: string): never {
  console.error(`\n❌ ${message}\n`);
  process.exit(1);
}

const routeName = process.argv[2];
const note = process.argv[3];

if (!routeName) {
  fail(
    `Usage: pnpm run attest-visual-baseline <route> ["why it does not render"]\n` +
      `   Routes: ${ROUTE_BASELINES.map((r) => r.name).join(', ')}`,
  );
}

const route = ROUTE_BASELINES.find((r) => r.name === routeName);
if (!route) {
  fail(
    `Unknown route '${routeName}'.\n` +
      `   Routes: ${ROUTE_BASELINES.map((r) => r.name).join(', ')}`,
  );
}

if (process.platform !== 'darwin') {
  fail(
    `Baselines are macOS-only (every file is '-darwin.png'), so an attestation ` +
      `written on ${process.platform} would describe bytes CI never renders. ` +
      `Run this on a macOS checkout.`,
  );
}

function git(args: string[]): string {
  return execFileSync('git', args, { encoding: 'utf8' });
}

/** Every baseline of every route — a regeneration rewrites them all. */
const allBaselines = ROUTE_BASELINES.flatMap((r) => r.baselineFiles);

const dirtyBefore = git(['status', '--porcelain', '--', ...allBaselines]).trim();
if (dirtyBefore) {
  fail(
    `Baseline files are already modified before regenerating, so this cannot tell ` +
      `your edits from the regeneration's:\n${dirtyBefore}\n\n   Commit or discard them first.`,
  );
}

console.log(`Regenerating every visual baseline to see whether [${routeName}] renders the same…`);
console.log('(The app must be running — see INTEGRATION_BASE_URL in .env.)\n');

try {
  execFileSync('pnpm', ['exec', 'playwright', 'test', 'visual', '--update-snapshots'], {
    stdio: 'inherit',
  });
} catch {
  fail(
    `The visual suite did not pass, so nothing here is safe to attest. ` +
      `Fix the failure (or start the app) and try again.`,
  );
}

const changed = git(['status', '--porcelain', '--', ...allBaselines]).trim();
if (changed) {
  fail(
    `The regeneration changed baselines, so this change DOES render:\n${changed}\n\n` +
      `   That is an ordinary visual change — review the new screenshots and commit ` +
      `them. An attestation is only for a change that renders identically.`,
  );
}

const attestations: AttestationMap = existsSync(ATTESTATION_PATH)
  ? (JSON.parse(readFileSync(ATTESTATION_PATH, 'utf8')) as AttestationMap)
  : {};

const entry: BaselineAttestation = {
  sourceSha256: hashFiles(route.sourceFiles),
  baselineSha256: hashFiles(route.baselineFiles),
  verifiedAt: new Date().toISOString().slice(0, 10),
  ...(note ? { note } : {}),
};

const next = { ...attestations, [route.name]: entry };
const ordered = Object.fromEntries(Object.entries(next).sort(([a], [b]) => a.localeCompare(b)));

writeFileSync(ATTESTATION_PATH, `${JSON.stringify(ordered, null, 2)}\n`);

console.log(`\n✅ [${routeName}] regenerated byte-identically; recorded in ${ATTESTATION_PATH}.`);
console.log(`   Commit that file. Editing ${route.sourceFiles.join(', ')} again voids the record.`);
